# https://ci.gitlab.com/lint
before_script:
    - export PATH="/Applications/Qt/5.4/clang_64/bin:$PATH"
    - export QTDIR="/Applications/Qt/5.4/clang_64"
    - cd src

build_job:
  type: build
  script:
    # http://doc.gitlab.com/ci/variables/README.html
    - echo "#define BUILD ""$CI_BUILD_ID" > build_number.h
    - qmake -project
    - qmake QOwnNotes.pro -r -spec macx-clang CONFIG+=x86_64
    - make
  only:
    - develop
    - master

deployment_job:
  type: deploy
  script:
    - $QTDIR/bin/macdeployqt QOwnNotes.app -dmg
  only:
    - develop
#    - master
