language: cpp

os:
  - linux
  - osx

env:
  - CONFIG=release
  - CONFIG=debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54creator
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew install qt5
      && brew install qt5-qmake
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - /opt/qt54/bin/qt54-env.sh 
  - cd src
  - /opt/qt54/bin/qmake -project
  - /opt/qt54/bin/qmake QOwnNotes.pro CONFIG+=$CONFIG
  - make

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/pbek/QOwnNotes --tags

deploy:
  provider: releases
  api_key:
    secure: EyOMTm+fzo7rWhRMfROH8/jeJnSFmLFz4pfD/HuFJI2ohayHJOIfASMdg0d7N2cGFS9G7iuPUmQ1S56YC8BSnEefc3lASB1i5hiSOMWJV+lO3N1JBFCWxCBzHc9Hs+XKwHwyhZ5iIYncx+JHPYRNWtUD+A6SZHiZ+sVI48gYMyA=
  file: src/QOwnNotes
  on:
    repo: pbek/QOwnNotes
    branch: master
    tags: true
