language: cpp

os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew install qt5
      && brew install qt5-qmake
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  -    cd src
    && qmake -v
    && qmake -project
    && qmake QOwnNotes.pro
    && make

notifications:
  email:
    - patrizio@bekerle.com
