language: cpp

os:
#  - linux
  - osx

env:
  global:
    - secure: Wt43koA55PGba7TsJ85f9vHyW4b/QfPh2Ywhw5+40sba5Us4Y3h+l23VyVjQbXuHfCGgC+t5+AABm1ubhL4MjCvxzS9BepjhNN92LPXoLfBRM2AHhNLWMKLLxt4T7OofjnLPw21l6cjjVrlZZojVbN4MnuG2IPUeUzoEBuA5TPE=
  matrix:
    - CONFIG=release
#    - CONFIG=debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && brew help
      && cd `brew --prefix`
      && git checkout HASH Library/Formula/qt5.rb
      && brew install qt5
      && brew switch qt5 5.4.2
      && ls -hal /usr/local/opt/qt5/bin
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - cd src
  - echo "#define BUILD ""$TRAVIS_BUILD_NUMBER" > build_number.h
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - qmake -project
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         qmake QOwnNotes.pro CONFIG+=$CONFIG
      ;
    else
         qmake QOwnNotes.pro CONFIG+=$CONFIG
      ;
    fi
  - make
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         otool -L ./QOwnNotes.app/Contents/MacOS/QOwnNotes
      && macdeployqt ./QOwnNotes.app
      && otool -L ./QOwnNotes.app/Contents/MacOS/QOwnNotes
      ;
    fi

before_deploy:
  # create debian package for linux and a disk image for OSX
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         VERSION_NUMBER=`cat version.h | sed "s/[^0-9,.]//g"`
      && cd ../travis
      && dpkg-deb -x QOwnNotes.deb build
      && mv ../src/QOwnNotes build/opt/QOwnNotes/
      && sed -i 's/VERSION_NUMBER/'"$VERSION_NUMBER"'/g' build/DEBIAN/control
      && dpkg -b build QOwnNotes.deb
      ;
    else
         ../travis/create-dmg.sh
      ;
    fi
  #
  # add a tag
  #
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER
      ;
    else
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER
      ;
    fi
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/pbek/QOwnNotes --tags

deploy:
  - provider: releases
    api_key:
        secure: EyOMTm+fzo7rWhRMfROH8/jeJnSFmLFz4pfD/HuFJI2ohayHJOIfASMdg0d7N2cGFS9G7iuPUmQ1S56YC8BSnEefc3lASB1i5hiSOMWJV+lO3N1JBFCWxCBzHc9Hs+XKwHwyhZ5iIYncx+JHPYRNWtUD+A6SZHiZ+sVI48gYMyA=
    file: QOwnNotes.deb
    skip_cleanup: true
    on:
        repo: pbek/QOwnNotes
        branch: master
        tags: false
        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = linux
  - provider: releases
    api_key:
        secure: EyOMTm+fzo7rWhRMfROH8/jeJnSFmLFz4pfD/HuFJI2ohayHJOIfASMdg0d7N2cGFS9G7iuPUmQ1S56YC8BSnEefc3lASB1i5hiSOMWJV+lO3N1JBFCWxCBzHc9Hs+XKwHwyhZ5iIYncx+JHPYRNWtUD+A6SZHiZ+sVI48gYMyA=
    file: QOwnNotes.dmg
    skip_cleanup: true
    on:
        repo: pbek/QOwnNotes
        branch: master
        tags: false
        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = osx

notifications:
  recipients:
    - $NOTIFICATION_EMAIL
  email:
    on_success: change
    on_failure: change
