# AppVeyor build configuration
os: unstable
install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - cd src
  - qmake QOwnNotes.pro
  - mingw32-make
