# AppVeyor build configuration
os: unstable

install:
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  # using a header file without MemoryBarrier, that causes the build to fail
  - copy appveyor\qopenglversionfunctions.h %QTDIR%\include\QtGui
  - cd src
  - qmake QOwnNotes.pro -r -spec win32-g++
#  - qmake QOwnNotes.pro -r -spec win32-g++ "CONFIG+=debug"
  - mingw32-make -v
  - mingw32-make
  - copy release\QOwnNotes.exe ..\appveyor\QOwnNotes

artifacts:
  # pushing entire folder as a zip archive
  - path: appveyor\QOwnNotes
    name: qownnotes_package

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: qownnotes_package
    draft: false
    prerelease: false
    auth_token:
      secure: spcyN/Dz3B2GXBPii8IywDLq6vfxC1SrN+xR2wMerFM7g2nTy0Lrh5agQONFoInR
