# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration
os: unstable
skip_tags: true

install:
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set RELEASE_PATH=appveyor\release

before_build:
  # getting submodules
  - git submodule init
  - git submodule update

build_script:
  # using a header file without MemoryBarrier, that causes the build to fail
  - copy appveyor\qopenglversionfunctions.h %QTDIR%\include\QtGui
  - cd src
  - echo "#define RELEASE \"AppVeyor\"" > release.h
  # setting the build number in the header file
  - "echo #define BUILD %APPVEYOR_BUILD_NUMBER% > build_number.h"
  - qmake QOwnNotes.pro -r -spec win32-g++
#  - qmake QOwnNotes.pro -r -spec win32-g++ "CONFIG+=debug"
  - mingw32-make
  # creating the release path
  - md ..\%RELEASE_PATH%
  # copy the binary to our release path
  - copy release\QOwnNotes.exe ..\%RELEASE_PATH%
  # copy OpenSSL DLLs to the release path
  - copy ..\appveyor\OpenSSL\libeay32.dll ..\%RELEASE_PATH%
  - copy ..\appveyor\OpenSSL\libssl32.dll ..\%RELEASE_PATH%
  - copy ..\appveyor\OpenSSL\ssleay32.dll ..\%RELEASE_PATH%
  - cd ..\%RELEASE_PATH%
  # fetching dependencies of QT app
  # http://doc.qt.io/qt-5/windows-deployment.html
  - windeployqt --release QOwnNotes.exe
  # this dll was missed by windeployqt
  - copy ..\libwinpthread-1.dll . /y
  # this dll didn't work when released by windeployqt
  - copy "..\libstdc++-6.dll" . /y

artifacts:
  # pushing entire folder as a zip archive
  - path: appveyor\release
    name: QOwnNotes

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: QOwnNotes
    draft: false
    prerelease: false
    auth_token:
      secure: spcyN/Dz3B2GXBPii8IywDLq6vfxC1SrN+xR2wMerFM7g2nTy0Lrh5agQONFoInR
    on:
      branch: master
